### ISSUE TITLE
Checklist refinements

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#481]
From user testing, the checklist needs some polishing.

Keyboard niceties when _editing_ a checklist:
- [x] priority A - Keyboard focus should start in the checklist name. 
- [x] priority A - The tab key should bring the user to the next logical field.
- [x] priority A - Use keyboard to add new row. (fixed: you can now tab to the Add New Row link and activate it with the keyboard)
- [ ] priority B - Location, date sighted, and date posted should default to the values in the previous row.
- [ ] priority C - When the user chooses save, and the last row plant name is blank, the row shouldn't be included in the save.

Other things:
- [x] priority A - Make the required fields more noticeable (e.g. the checklist name). This is related to tab order and keyboard focus. Users would add plant names, click save, and then be flustered when they hadn't entered a checklist name. Also it's not obvious if the name or comment is the required field.
- [ ] priority A - Add the Found column to the view and edit views. It already exists in the Excel export.
- [ ] priority B - When a user views their checklist, any images they've added don't appear, even if the image has been approved.
- [ ] priority B - In view mode, the link should be linked to a larger version of the image.
- [x] priority B - The autosuggest field behaves incorrectly in FireFox. Type a few characters, e.g. "Acer" and then selecting a suggested Acer using the mouse does not work. This is not an issue in Chrome. [note: John not able to reproduce bug, requests opening a separate issue w/repro. steps if Sid still sees it]
